"""empty message

Revision ID: 882a0ca77e07
Revises: 7a9b4d901b46
Create Date: 2019-12-18 10:14:02.197157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882a0ca77e07'
down_revision = '7a9b4d901b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_nickname_key', 'users', type_='unique')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_nickname_key', 'users', ['nickname'])
    # ### end Alembic commands ###
