"""empty message

Revision ID: 09bd9bb86f80
Revises: 017b6640f74b
Create Date: 2020-01-12 18:12:13.136696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09bd9bb86f80'
down_revision = '017b6640f74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_tokens', 'provider', existing_type=sa.String(50), type_=sa.String(16))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_tokens', 'provider', existing_type=sa.String(16), type_=sa.String(50))
    # ### end Alembic commands ###
