"""empty message

Revision ID: 4a33c1a875cd
Revises: 09bd9bb86f80
Create Date: 2020-01-12 18:54:56.563997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a33c1a875cd'
down_revision = '09bd9bb86f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oauth_clients', ['client_id'])
    op.create_unique_constraint(None, 'oauth_clients', ['id'])
    op.alter_column('oauth_tokens', 'token',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'oauth_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_tokens', type_='unique')
    op.alter_column('oauth_tokens', 'token',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'oauth_clients', type_='unique')
    op.drop_constraint(None, 'oauth_clients', type_='unique')
    # ### end Alembic commands ###
