"""empty message

Revision ID: ae3bad999d25
Revises: 5e8128e2c29a
Create Date: 2019-12-24 01:29:23.648571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3bad999d25'
down_revision = '5e8128e2c29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'flask_dance_oauth', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flask_dance_oauth', type_='unique')
    # ### end Alembic commands ###
