"""empty message

Revision ID: c2e80d98dd7a
Revises: fd21f5a4b9bb
Create Date: 2020-01-11 23:44:30.870609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e80d98dd7a'
down_revision = 'fd21f5a4b9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'is_done', nullable=False, new_column_name="done")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'done', nullable=False, new_column_name="is_done")
    # ### end Alembic commands ###
