"""empty message

Revision ID: d76385401986
Revises: 4a33c1a875cd
Create Date: 2020-01-12 20:40:52.154832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd76385401986'
down_revision = '4a33c1a875cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_clients', 'client_handle', nullable=False, new_column_name="handle")
    op.alter_column('oauth_clients', 'client_secret', nullable=False, new_column_name="secret")
    op.alter_column('oauth_clients', 'id', nullable=False, new_column_name="identifier")
    op.alter_column('oauth_clients', 'client_id', nullable=False, new_column_name="id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_clients', 'handle', nullable=False, new_column_name="client_handle")
    op.alter_column('oauth_clients', 'secret', nullable=False, new_column_name="client_secret")
    op.alter_column('oauth_clients', 'identifier', nullable=False, new_column_name="id")
    op.alter_column('oauth_clients', 'id', nullable=False, new_column_name="client_id")
    # ### end Alembic commands ###
