"""empty message

Revision ID: fae3f287414e
Revises: 8735c4ef85a0
Create Date: 2020-01-07 22:15:24.553356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae3f287414e'
down_revision = '8735c4ef85a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'oauth_tokens', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'oauth_tokens', type_='unique')
    # ### end Alembic commands ###
